### ISSUE TITLE
[ENHANCEMENT] Custom League Logo

### ISSUE THREAD

**Issue by zekethebeast** [nmelhado/league-page#106]
Is there currently a way to add a custom league logo to show up when on the site? I've been loving the site and have been making little tweaks here and there, but can't figure out how to add our league logo to show up throughout.

**Comment by nmelhado** [comment]
Replace `static/badge.png` with your league logo. I recommend maintaining the same dimensions, but otherwise change it to whatever you'd like. If you do that and you don't see the change, it's likely just cached in your browser. Just do a hard reload or visit the page in incognito mode to see the update.

**Comment by nmelhado** [comment]
If that doesn't fix it, just reopen this and I'll help you troubleshoot.
