### ISSUE TITLE
[ENHANCEMENT] League Betting Section

### ISSUE THREAD

**Issue by dtsong** [nmelhado/league-page#108]
**Is your feature request related to a problem? Please describe.**
This is definitely more of a "nice-to-have", but it would add another aspect to the site that would help make it feel more like home for dynasty owners.

**Describe the solution you'd like**
A tab on the website page that keeps track of ongoing bets between league-mates. Probably something along the lines of having these things in a table of sorts:
* Between which owners
* What they are betting (Ex. money, a draft pick swap, doing something embarrassing in public, etc)
* Conditions

**Additional context**
Definitely open to ideas on that on the implementation details or feedback, but think that would be something pretty cool! I am also happy to help with development effort although I am definitely quite green to JavaScript so I definitely want to test and work on it step-by-step before it gets merged into the main repository.

**Comment by nmelhado** [comment]
I think this would require you to add authenticated accounts to the site. This is definitely doable, but is realistically outside the scope of this project. It would be very hard to implement this in a safe and reusable way otherwise.

I'm going to close this, but feel free to open a discussion if you want pointers on how to add this to your page yourself!
