### ISSUE TITLE
[BUG] Standings are pulling division record into overall record

### ISSUE THREAD

**Issue by sux1536** [nmelhado/league-page#276]
My league uses median scoring and has different divisions. After Week 2, it says the top team is 6-0 (2-0 from H2H, 2-0 from median scoring, but it is also being counted 2-0 from beating a division opponent). I like having the divisions standings as a separate stat, but it should not be included in the overall record which should be 4-0.

On a separate issue, all the season averages are pulling from the 6 games it's saying is played instead of just the 2 weeks that have been played.

I hope all this makes sense, I love your work man~!!

**Comment by JimNayzium** [comment]
I will second this happening. 
What I kind of think is happening as I have been digging deep into it is maybe the median calculation of the league-page was happening PRIOR to Sleeper actually doing this calculation for us.

Because it says I have 6 wins in the json pulled from sleeper not 3 plus 3 median wins. 

Then it is adding another median win to the win total pulled from Sleeper possibly?

I am curiuos if we need to shut off the median scoring comparisons inside the league-page modules all together? 

Your stuff is fantastic as stated above though! Just trying to do some customizing and noticing this as well.

I have not decided about the divisions yet, but at first glance I don't think mine is pulling the division wins separtely and counting them in the total. But it is counting the overall wins pulled from sleeper which is 6 for 3 weeks as undefeatd but it gives me 9 wins on the standings pages... and stepping through it in the leagueStandings.js I can console.log out these lines and see it happening I think.

`	if (medianMatch == true) {
			for (let i = 0; i < 2; i++) {
				if (matchups[matchupKey][i].points > medianScore) {
          let winsNumber = standingsData[matchups[matchupKey][i].rosterID].wins;
          standingsData[matchups[matchupKey][i].rosterID].wins++;
          
          if (matchups[matchupKey][i].rosterID === 1) {
            console.log('\n\n\n============ * Called From * ==========================');
            console.log('\x1b[32mIN: winsNumber in MedianMatch Loop :');
            console.log('    \x1b[34m winsNumber for rosterID: ' + matchups[matchupKey][i].rosterID + '   \x1b[0m= \x1b[35m', winsNumber);
            console.log('\x1b[0m=========================================================\n\n\n');
          }       
        

				} else if (matchups[matchupKey][i].points < medianScore) {
					
          standingsData[matchups[matchupKey][i].rosterID].losses++;
				
        } else if (matchups[matchupKey][i].points == medianScore) {
				
          standingsData[matchups[matchupKey][i].rosterID].ties++;
				
        }
			}
		}`

**Comment by JimNayzium** [comment]
And to follow up - I just did this:

`  const medianMatch = false;  //leagueData.settings.league_average_match == 1;`

and it made it all accurate, so I think what was happening was Sleeper wasn't allowing us to play vs the median when this oriignal code base was designed and written and he built into the median comparison. Now that sleeper includes that in our wins it doubles those in the outcome of the leagueStandings.js I think.

**Comment by sux1536** [comment]
I just went in and added the "false; //" and it looks like everything is fixed. Thank you for diving into it!

**Comment by JimNayzium** [comment]
Sure thing. 
Now we just need to figure out how to fix the leagueRecords.js page when the league does snot have playoffs!
I have a league that does such crazy playoffs I cna't use the sleeper playoffs setting to ON it has to be oFF nad we do the playoffs on paper sort of...

But that ruins the league-page's code for figuring out records and all time matchups and such so far!
